[project]
name = "metapkg"
version = "0.1.0"
description = "CLI tool to manage pyproject.toml and generate requirements.txt"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "toml>=0.10.2",
    "tomli-w>=1.2.0",
    "typer>=0.15.3",
]
